const fs=require('fs');const path=require('path');const {chromium}=require('playwright');const fetch=require('node-fetch');(async()=>{const base='https://ai-lish.github.io/ai-learning/hkdse/';const pages=fs.readdirSync('.').filter(f=>/(\.html|\.json)$/.test(f));await fs.promises.mkdir('health', {recursive:true});await fs.promises.mkdir('health/screenshots', {recursive:true});await fs.promises.mkdir('health/lighthouse', {recursive:true});let summaryLines=[];for(const file of pages){try{const url=base+file;const start=Date.now();const res=await fetch(url);const time=Date.now()-start;const status=res.status;const body=await res.text();const size=Buffer.byteLength(body,'utf8');const first50=body.split('\n').slice(0,50).join('\n');await fs.promises.writeFile(path.join('health', file+'_summary.txt'),`URL: ${url}\nStatus: ${status}\nSize: ${size}\nTimeMs: ${time}\nFirst50:\n${first50}`);summaryLines.push(`${file},${status},${size},${time}`);const resources=[];const hrefs=[...body.matchAll(/(?:href|src)=["']([^"']+)["']/g)].slice(0,200).map(m=>m[1]);for(const r of hrefs){let rurl=r;try{if(r.startsWith('//')) rurl='https:'+r; else if(r.startsWith('/')) rurl='https://ai-lish.github.io'+r; else if(!/^https?:/.test(r)) rurl=new URL(r,url).href;}catch(e){rurl=r;}resources.push(rurl);}await fs.promises.writeFile(path.join('health', file+'_resources.csv'),['resource,status'].concat(await Promise.all(resources.map(async r=>{try{const rr=await fetch(r,{method:'HEAD'});return `${r},${rr.status}`}catch(e){return `${r},ERROR`}}))).join('\n')); // render with playwright
const browser=await chromium.launch();const pageObj=await browser.newPage();const consoleMsgs=[];pageObj.on('console',m=>consoleMsgs.push(`${m.type()}: ${m.text()}`));const failedRequests=[];pageObj.on('requestfailed',req=>failedRequests.push(`${req.url()} ${req.failure()?.errorText||''}`));await pageObj.goto(url,{waitUntil:'networkidle',timeout:30000});await pageObj.screenshot({path:path.join('health','screenshots',file.replace(/\W/g,'_')+'.png'),fullPage:true});await fs.promises.writeFile(path.join('health', file+'_console.log'),consoleMsgs.join('\n'));
await fs.promises.writeFile(path.join('health', file+'_network.log'),failedRequests.join('\n'));
await browser.close();
}catch(e){await fs.promises.writeFile(path.join('health', file+'_summary.txt'),`ERROR: ${e.stack||e}`);summaryLines.push(`${file},ERROR,0,0`);}}
await fs.promises.writeFile('health_summary.txt',summaryLines.join('\n'));
// Lighthouse for two pages
const {execSync}=require('child_process');const lighthousePages=['p2-review-enhanced.html','review.html'];for(const f of lighthousePages){try{const url=base+f;const outHtml=path.join('health','lighthouse',f.replace(/\W/g,'_')+'_report.html');const outJson=path.join('health','lighthouse',f.replace(/\W/g,'_')+'_report.json');console.log('Running lighthouse for',url);execSync(`npx lighthouse ${url} --output=json --output=html --output-path=${outHtml} --quiet`,{stdio:['ignore','ignore','ignore'],env:process.env}); // npx writes files; move json
// npx lighthouse with --output-path writes basename; ensure json present
}catch(e){await fs.promises.writeFile(path.join('health','lighthouse',f.replace(/\W/g,'_')+'_error.txt'),e.stack||String(e));}}
// aggregate report
let report='# Audit Report\n\n';report+='See individual files in health/\n';await fs.promises.writeFile(path.join('health','report.md'),report);
console.log('DONE');process.exit(0);})();